[platformio]
default_envs = waveshare-esp32-s3-touch-amoled-2p06-mictest

[env:waveshare-esp32-s3-touch-amoled-2p06-mictest]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_ldf_mode = deep+
