[platformio]
default_envs = waveshare-esp32-s3-touch-amoled-2p06

[env:waveshare-esp32-s3-touch-amoled-2p06]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DGROQWATCH_LOW_LOG_BUILD=1
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32s3/include/espressif__esp32-camera/conversions/include
lib_ldf_mode = deep+
lib_deps =
    https://github.com/moononournation/Arduino_GFX.git
    https://github.com/yuttapichai/Arduino_DriveBus.git
    https://github.com/lewisxhe/SensorLib.git
    https://github.com/lewisxhe/XPowersLib.git
    bblanchon/ArduinoJson@^7.1.0
    bitbank2/JPEGDEC@^1.8.2
